apiVersion: v1
kind: Service
metadata:
  name: truthserum
  namespace: quietbuild
  labels:
    app: truthserum
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: truthserum
