services:
  node:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/workspaces/qbos:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/qbos

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: qbos
    ports:
      - "5432:5432"
